/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type BitmapClosed = {
  airdrop: Address;
  bitmap: Address;
  owner: Address;
};

export type BitmapClosedArgs = BitmapClosed;

export function getBitmapClosedEncoder(): Encoder<BitmapClosedArgs> {
  return getStructEncoder([
    ['airdrop', getAddressEncoder()],
    ['bitmap', getAddressEncoder()],
    ['owner', getAddressEncoder()],
  ]);
}

export function getBitmapClosedDecoder(): Decoder<BitmapClosed> {
  return getStructDecoder([
    ['airdrop', getAddressDecoder()],
    ['bitmap', getAddressDecoder()],
    ['owner', getAddressDecoder()],
  ]);
}

export function getBitmapClosedCodec(): Codec<BitmapClosedArgs, BitmapClosed> {
  return combineCodec(getBitmapClosedEncoder(), getBitmapClosedDecoder());
}
