/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type ControllerInitialized = {
  authority: Address;
  feeVault: Address;
  createFee: bigint;
  claimFee: bigint;
  bump: number;
  timestamp: bigint;
};

export type ControllerInitializedArgs = {
  authority: Address;
  feeVault: Address;
  createFee: number | bigint;
  claimFee: number | bigint;
  bump: number;
  timestamp: number | bigint;
};

export function getControllerInitializedEncoder(): Encoder<ControllerInitializedArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['feeVault', getAddressEncoder()],
    ['createFee', getU64Encoder()],
    ['claimFee', getU64Encoder()],
    ['bump', getU8Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getControllerInitializedDecoder(): Decoder<ControllerInitialized> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['feeVault', getAddressDecoder()],
    ['createFee', getU64Decoder()],
    ['claimFee', getU64Decoder()],
    ['bump', getU8Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getControllerInitializedCodec(): Codec<
  ControllerInitializedArgs,
  ControllerInitialized
> {
  return combineCodec(
    getControllerInitializedEncoder(),
    getControllerInitializedDecoder()
  );
}
