/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type FeesCollected = {
  controller: Address;
  authority: Address;
  feeVault: Address;
  amount: bigint;
  timestamp: bigint;
};

export type FeesCollectedArgs = {
  controller: Address;
  authority: Address;
  feeVault: Address;
  amount: number | bigint;
  timestamp: number | bigint;
};

export function getFeesCollectedEncoder(): Encoder<FeesCollectedArgs> {
  return getStructEncoder([
    ['controller', getAddressEncoder()],
    ['authority', getAddressEncoder()],
    ['feeVault', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getFeesCollectedDecoder(): Decoder<FeesCollected> {
  return getStructDecoder([
    ['controller', getAddressDecoder()],
    ['authority', getAddressDecoder()],
    ['feeVault', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getFeesCollectedCodec(): Codec<
  FeesCollectedArgs,
  FeesCollected
> {
  return combineCodec(getFeesCollectedEncoder(), getFeesCollectedDecoder());
}
