/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type MasterInitialized = {
  authority: Address;
  feeVault: Address;
  protocolFee: bigint;
  initControllerFee: bigint;
  withdrawFee: bigint;
  bump: number;
  timestamp: bigint;
};

export type MasterInitializedArgs = {
  authority: Address;
  feeVault: Address;
  protocolFee: number | bigint;
  initControllerFee: number | bigint;
  withdrawFee: number | bigint;
  bump: number;
  timestamp: number | bigint;
};

export function getMasterInitializedEncoder(): Encoder<MasterInitializedArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['feeVault', getAddressEncoder()],
    ['protocolFee', getU64Encoder()],
    ['initControllerFee', getU64Encoder()],
    ['withdrawFee', getU64Encoder()],
    ['bump', getU8Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getMasterInitializedDecoder(): Decoder<MasterInitialized> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['feeVault', getAddressDecoder()],
    ['protocolFee', getU64Decoder()],
    ['initControllerFee', getU64Decoder()],
    ['withdrawFee', getU64Decoder()],
    ['bump', getU8Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getMasterInitializedCodec(): Codec<
  MasterInitializedArgs,
  MasterInitialized
> {
  return combineCodec(
    getMasterInitializedEncoder(),
    getMasterInitializedDecoder()
  );
}
