/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type TokensDeposited = {
  airdrop: Address;
  amount: bigint;
  newSupply: bigint;
  depositor: Address;
  timestamp: bigint;
};

export type TokensDepositedArgs = {
  airdrop: Address;
  amount: number | bigint;
  newSupply: number | bigint;
  depositor: Address;
  timestamp: number | bigint;
};

export function getTokensDepositedEncoder(): Encoder<TokensDepositedArgs> {
  return getStructEncoder([
    ['airdrop', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['newSupply', getU64Encoder()],
    ['depositor', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getTokensDepositedDecoder(): Decoder<TokensDeposited> {
  return getStructDecoder([
    ['airdrop', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['newSupply', getU64Decoder()],
    ['depositor', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getTokensDepositedCodec(): Codec<
  TokensDepositedArgs,
  TokensDeposited
> {
  return combineCodec(getTokensDepositedEncoder(), getTokensDepositedDecoder());
}
