/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { DROPSY_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const INITIALIZE_BITMAP_DISCRIMINATOR = new Uint8Array([
  25, 109, 200, 45, 209, 118, 74, 69,
]);

export function getInitializeBitmapDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_BITMAP_DISCRIMINATOR
  );
}

export type InitializeBitmapInstruction<
  TProgram extends string = typeof DROPSY_PROGRAM_ADDRESS,
  TAccountBitmap extends string | IAccountMeta<string> = string,
  TAccountAirdrop extends string | IAccountMeta<string> = string,
  TAccountOwner extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountBitmap extends string
        ? WritableAccount<TAccountBitmap>
        : TAccountBitmap,
      TAccountAirdrop extends string
        ? WritableAccount<TAccountAirdrop>
        : TAccountAirdrop,
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            IAccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeBitmapInstructionData = {
  discriminator: ReadonlyUint8Array;
  id: number;
  total: bigint;
};

export type InitializeBitmapInstructionDataArgs = {
  id: number;
  total: number | bigint;
};

export function getInitializeBitmapInstructionDataEncoder(): Encoder<InitializeBitmapInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['id', getU8Encoder()],
      ['total', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_BITMAP_DISCRIMINATOR })
  );
}

export function getInitializeBitmapInstructionDataDecoder(): Decoder<InitializeBitmapInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['id', getU8Decoder()],
    ['total', getU64Decoder()],
  ]);
}

export function getInitializeBitmapInstructionDataCodec(): Codec<
  InitializeBitmapInstructionDataArgs,
  InitializeBitmapInstructionData
> {
  return combineCodec(
    getInitializeBitmapInstructionDataEncoder(),
    getInitializeBitmapInstructionDataDecoder()
  );
}

export type InitializeBitmapAsyncInput<
  TAccountBitmap extends string = string,
  TAccountAirdrop extends string = string,
  TAccountOwner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  bitmap?: Address<TAccountBitmap>;
  airdrop: Address<TAccountAirdrop>;
  owner: TransactionSigner<TAccountOwner>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: InitializeBitmapInstructionDataArgs['id'];
  total: InitializeBitmapInstructionDataArgs['total'];
};

export async function getInitializeBitmapInstructionAsync<
  TAccountBitmap extends string,
  TAccountAirdrop extends string,
  TAccountOwner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_PROGRAM_ADDRESS,
>(
  input: InitializeBitmapAsyncInput<
    TAccountBitmap,
    TAccountAirdrop,
    TAccountOwner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitializeBitmapInstruction<
    TProgramAddress,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountOwner,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? DROPSY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    bitmap: { value: input.bitmap ?? null, isWritable: true },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    owner: { value: input.owner ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.bitmap.value) {
    accounts.bitmap.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([98, 105, 116, 109, 97, 112])),
        getAddressEncoder().encode(expectAddress(accounts.airdrop.value)),
        getU8Encoder().encode(expectSome(args.id)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.bitmap),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeBitmapInstructionDataEncoder().encode(
      args as InitializeBitmapInstructionDataArgs
    ),
  } as InitializeBitmapInstruction<
    TProgramAddress,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountOwner,
    TAccountSystemProgram
  >;

  return instruction;
}

export type InitializeBitmapInput<
  TAccountBitmap extends string = string,
  TAccountAirdrop extends string = string,
  TAccountOwner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  bitmap: Address<TAccountBitmap>;
  airdrop: Address<TAccountAirdrop>;
  owner: TransactionSigner<TAccountOwner>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: InitializeBitmapInstructionDataArgs['id'];
  total: InitializeBitmapInstructionDataArgs['total'];
};

export function getInitializeBitmapInstruction<
  TAccountBitmap extends string,
  TAccountAirdrop extends string,
  TAccountOwner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_PROGRAM_ADDRESS,
>(
  input: InitializeBitmapInput<
    TAccountBitmap,
    TAccountAirdrop,
    TAccountOwner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeBitmapInstruction<
  TProgramAddress,
  TAccountBitmap,
  TAccountAirdrop,
  TAccountOwner,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? DROPSY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    bitmap: { value: input.bitmap ?? null, isWritable: true },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    owner: { value: input.owner ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.bitmap),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeBitmapInstructionDataEncoder().encode(
      args as InitializeBitmapInstructionDataArgs
    ),
  } as InitializeBitmapInstruction<
    TProgramAddress,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountOwner,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeBitmapInstruction<
  TProgram extends string = typeof DROPSY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    bitmap: TAccountMetas[0];
    airdrop: TAccountMetas[1];
    owner: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializeBitmapInstructionData;
};

export function parseInitializeBitmapInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitializeBitmapInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      bitmap: getNextAccount(),
      airdrop: getNextAccount(),
      owner: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeBitmapInstructionDataDecoder().decode(instruction.data),
  };
}
